# -*- coding: utf-8 -*-
"""project_heart_disease

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui3UNZqu79yvA_ncYe9_lyrybvw3GZIC
"""

import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import RobustScaler, OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

# ignorar todos os warnings
warnings.filterwarnings('ignore')

# definir o random state
RANDOM_STATE = 13

# carregar diretamente
data = pd.read_csv('heart_disease.csv')
data.head()

# verificando dados
display(data.info())

# verificando dados nulos
display(data.isna().sum())

# Verificando os valores únicos e a contagem
print("Contagem por categoria de Álcool:")
display(data['Alcohol Consumption'].value_counts(dropna=False))

# Calculando a porcentagem de cada categoria (incluindo os nulos)
print("\nDistribuição Percentual:")
display(data['Alcohol Consumption'].value_counts(dropna=False, normalize=True) * 100)

# Criando um gráfico de barras para visualizar
plt.figure(figsize=(10, 6))
data['Alcohol Consumption'].value_counts(dropna=False).plot(kind='bar', color='skyblue')
plt.title('Distribuição do Consumo de Álcool (incluindo nulos)')
plt.xlabel('Nível de Consumo')
plt.ylabel('Quantidade de Pacientes')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 1. Calculando quantas linhas restariam se deletássemos QUALQUER linha com NaN
linhas_com_algum_nulo = data.isna().any(axis=1).sum()
total_linhas = len(data)
linhas_restantes = total_linhas - linhas_com_algum_nulo

print(f"Total de linhas original: {total_linhas}")
print(f"Linhas que possuem pelo menos um valor nulo: {linhas_com_algum_nulo}")
print(f"Linhas que restariam após o drop total: {linhas_restantes}")
print(f"Porcentagem de perda: {(linhas_com_algum_nulo/total_linhas)*100:.2f}%")

# 1. Selecionando apenas as colunas numéricas
numeric_cols = data.select_dtypes(include=['float64']).columns

# 2. Criando subplots para histogramas e boxplots
plt.figure(figsize=(15, 20))
for i, col in enumerate(numeric_cols):
    # Histograma para ver Assimetria
    plt.subplot(len(numeric_cols), 2, 2*i + 1)
    sns.histplot(data[col], kde=True, color='teal')
    plt.title(f'Distribuição: {col} (Skew: {data[col].skew():.2f})')

    # Boxplot para ver Outliers
    plt.subplot(len(numeric_cols), 2, 2*i + 2)
    sns.boxplot(x=data[col], color='lightcoral')
    plt.title(f'Outliers: {col}')

plt.tight_layout()
plt.show()

# Contagem absoluta
print("Contagem de Heart Disease Status:")
print(data['Heart Disease Status'].value_counts())

# Proporção percentual
print("\nProporção Percentual:")
print(data['Heart Disease Status'].value_counts(normalize=True) * 100)

# Visualização gráfica
plt.figure(figsize=(8, 5))
sns.countplot(x='Heart Disease Status', data=data, palette='viridis')
plt.title('Distribuição da Variável Alvo (Target)')
plt.show()

# 1. Separando as features (x) e o alvo (y)
y = data['Heart Disease Status'].map({'Yes': 1, 'No': 0})
x = data.drop(columns=['Heart Disease Status'])

# 2. Dividindo em treino e teste (80/20) - x em minúsculo
# O stratify garante que a proporção de doentes seja igual nos dois grupos
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

# 3. Identificando as colunas usando o x minúsculo
num_features = x.select_dtypes(include=['float64']).columns.tolist()
cat_features = x.select_dtypes(include=['object']).columns.tolist()

# 4. Criando os transformadores
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

# 5. Combinando no ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
])

# 6. Criando o Pipeline Final (Baseline Perceptron)
baseline_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', Perceptron(random_state=RANDOM_STATE))
])

# 7. Treinando o modelo com x_train
baseline_model.fit(x_train, y_train)

# 8. Avaliação com x_test
y_pred = baseline_model.predict(x_test)

print("--- Relatório de Classificação - Perceptron Baseline ---")
print(classification_report(y_test, y_pred))

# Plotando a Matriz de Confusão
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Disease', 'Heart Disease'])
disp.plot(cmap='Blues')
plt.title('Matriz de Confusão - Perceptron')
plt.show()

# 1. Criando os novos transformadores (Pré-processamento Otimizado)
# Usamos RobustScaler para lidar melhor com a variação dos dados
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler())
])

# Para categorias, continuamos com a moda (most_frequent) e OneHotEncoder
cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

# 2. Combinando no novo ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
])

# 3. Criando o Pipeline Final (Baseline Perceptron Otimizado)
# class_weight='balanced' ajuda a compensar o desbalanceamento de 80/20
baseline_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', Perceptron(
        random_state=RANDOM_STATE,
        class_weight='balanced',
        max_iter=1000,
        tol=1e-3
    ))
])

# 4. Treinando o modelo
baseline_model.fit(x_train, y_train)

# 5. Avaliação Final
y_pred = baseline_model.predict(x_test)

# --- Exibição dos Resultados ---
print("--- Relatório de Classificação - Perceptron Baseline Otimizado ---")
print(classification_report(y_test, y_pred))

# Plotando a Matriz de Confusão
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Disease', 'Heart Disease'])
disp.plot(cmap='Blues', values_format='d')
plt.title('Matriz de Confusão - Perceptron Otimizado')
plt.show()

# Extraindo pesos e bias do Perceptron Otimizado
pesos = baseline_model.named_steps['classifier'].coef_[0]
bias = baseline_model.named_steps['classifier'].intercept_

# Gerando os nomes das colunas
feature_names = num_features + list(baseline_model.named_steps['preprocessor'].transformers_[1][1].named_steps['onehot'].get_feature_names_out(cat_features))

# Criando um DataFrame para facilitar a visualização
df_pesos = pd.DataFrame({'Feature': feature_names, 'Peso': pesos})
print(f"\nBias do Perceptron: {bias}")
print(df_pesos.sort_values(by='Peso', ascending=False))

# 1. Criando o Pipeline para a Árvore de Decisão
# Usamos class_weight='balanced' para manter o foco nos 20% de doentes
tree_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        random_state=RANDOM_STATE,
        class_weight='balanced',
        max_depth=4 # Limitamos a profundidade para a árvore não "decorar" os dados (overfitting)
    ))
])

# 2. Treinando o modelo
tree_model.fit(x_train, y_train)

# 3. Fazendo as previsões
y_pred_tree = tree_model.predict(x_test)

# 4. Relatório de Classificação
print("--- Relatório de Classificação - Árvore de Decisão ---")
print(classification_report(y_test, y_pred_tree))

# 5. Matriz de Confusão
plt.figure(figsize=(8, 6))
cm_tree = confusion_matrix(y_test, y_pred_tree)
disp_tree = ConfusionMatrixDisplay(confusion_matrix=cm_tree, display_labels=['No Disease', 'Heart Disease'])
disp_tree.plot(cmap='Greens', values_format='d')
plt.title('Matriz de Confusão - Árvore de Decisão')
plt.show()

# 6. Visualizando a Árvore (O desenho das regras)
plt.figure(figsize=(20, 10))
# Pegamos os nomes das colunas após o processamento para o gráfico ficar legível
feature_names = num_features + list(tree_model.named_steps['preprocessor'].transformers_[1][1].named_steps['onehot'].get_feature_names_out(cat_features))

plot_tree(tree_model.named_steps['classifier'],
          feature_names=feature_names,
          class_names=['No', 'Yes'],
          filled=True, rounded=True, fontsize=10)
plt.title("Regras de Decisão da Árvore")
plt.show()

# 1. Definindo o Espaço de Busca (Hiperparâmetros)
# Testaremos diferentes profundidades e critérios de divisão
param_grid = {
    'classifier__max_depth': [3, 4, 5, 6, 8, 10],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__criterion': ['gini', 'entropy']
}

# 2. Configurando o Grid Search com Validação Cruzada (CV=5)
# O scoring='f1' é ideal porque seu dataset é desbalanceado (80/20)
grid_search = GridSearchCV(
    tree_model,
    param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# 3. Executando a busca nos dados de treino
grid_search.fit(x_train, y_train)

# 4. Melhores parâmetros encontrados
print(f"Melhores Hiperparâmetros: {grid_search.best_params_}")

# 5. Avaliando o modelo otimizado no conjunto de teste
best_tree = grid_search.best_estimator_
y_pred_best = best_tree.predict(x_test)

print("\n--- Relatório de Classificação - Árvore Otimizada ---")
print(classification_report(y_test, y_pred_best))

# 1. Expandindo o Espaço de Busca
param_grid_expanded = {
    'classifier__criterion': ['gini', 'entropy'],
    'classifier__max_depth': [5, 6, 7, 8, 12],
    'classifier__min_samples_split': [10, 20, 50],
    'classifier__min_samples_leaf': [5, 10, 20],
    'classifier__max_features': [None, 'sqrt', 'log2'],
    'classifier__ccp_alpha': [0.0, 0.001, 0.01]
}

# 2. Configurando a Busca
# Dica: use scoring='recall' ou 'f1' para focar nos doentes!
grid_search_v2 = GridSearchCV(
    tree_model,
    param_grid_expanded,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search_v2.fit(x_train, y_train)

print(f"Novos Melhores Hiperparâmetros: {grid_search_v2.best_params_}")

# 3. Avaliação do novo modelo
best_tree_v2 = grid_search_v2.best_estimator_
y_pred_v2 = best_tree_v2.predict(x_test)

print("\n--- Relatório de Classificação - Árvore Otimizada V2 ---")
print(classification_report(y_test, y_pred_v2))

# 1. Pipeline com Random Forest
rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        random_state=RANDOM_STATE,
        class_weight='balanced',
        n_jobs=-1 # Usa todos os núcleos do seu PC para ser rápido
    ))
])

# 2. Hiperparâmetros para a Floresta
param_grid_rf = {
    'classifier__n_estimators': [100, 200], # Quantidade de árvores
    'classifier__max_depth': [8, 12, 15],
    'classifier__min_samples_leaf': [5, 10]
}

# 3. Busca com Validação Cruzada
grid_rf = GridSearchCV(rf_model, param_grid_rf, cv=5, scoring='f1', verbose=1)
grid_rf.fit(x_train, y_train)

# 4. Resultados
print(f"Melhores parâmetros RF: {grid_rf.best_params_}")
y_pred_rf = grid_rf.best_estimator_.predict(x_test)

print("\n--- Relatório de Classificação - RANDOM FOREST ---")
print(classification_report(y_test, y_pred_rf))

# Extraindo a importância das features do Random Forest
importances = grid_rf.best_estimator_.named_steps['classifier'].feature_importances_
feature_names = num_features + list(grid_rf.best_estimator_.named_steps['preprocessor'].transformers_[1][1].named_steps['onehot'].get_feature_names_out(cat_features))

# Criando o DataFrame e plotando
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 8))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df.head(15), palette='magma')
plt.title('Top 15 Variáveis Mais Importantes - Random Forest')
plt.show()